-- 다중칼럼!! 

SELECT GRADE "학년", NAME "이름" , HEIGHT "키" 
FROM T_STUDENT 
WHERE (GRADE , WEIGHT ) IN 
	(SELECT GRADE , MAX(HEIGHT) FROM T_STUDENT GROUP BY GRADE) 
ORDER BY GRADE ASC	
;

-- 

SELECT p.PROFNO , p.NAME , p.HIREDATE , d.DNAME 
FROM T_PROFESSOR p, T_DEPARTMENT d
WHERE p.DEPTNO = d.DEPTNO 
	AND (p.DEPTNO , p.HIREDATE ) 
	IN (SELECT DEPTNO , MIN(HIREDATE ) FROM T_PROFESSOR GROUP BY DEPTNO) 
ORDER BY d.DNAME ASC 	
;


--
SELECT NAME , POST , PAY 
FROM T_EMP2 
WHERE (POST , PAY ) IN
(SELECT NVL(POST , ' ') , MAX(PAY ) FROM T_EMP2 GROUP BY NVL(POST, ' '))
ORDER BY pay ASC 
;

--

SELECT d.DNAME , e.NAME , e.PAY 
FROM T_EMP2 e , T_DEPT2 d
WHERE e.DEPTNO  = d.DCODE 
	AND e.PAY < ALL (SELECT AVG(PAY ) FROM T_EMP2 GROUP BY DEPTNO )
ORDER BY PAY ASC
;

-- 
SELECT AVG(b.pay) FROM T_EMP2 b WHERE '과장' = b.POST



SELECT a.NAME , NVL(a.POST, ' ') , PAY 
FROM T_EMP2 a
WHERE a.PAY >= (SELECT AVG(b.pay ) FROM T_EMP2 b WHERE NVL(a.POST, ' ') = NVL(b.POST, ' ') )
;

SELECT NAME , SUBSTR( JUMIN , 1, 6) 
FROM T_STUDENT
WHERE DEPTNO1 = 101;




