DELETE FROM T_STUDENT WHERE GRADE = 4;

SELECT * FROM T_STUDENT ;

UPDATE T_STUDENT 
SET STUDNO = 9091, NAME = '김수진', ID = 'sooplus', DEPTNO1 = 101, GRADE = 2, PROFNO = 1004;



SELECT NAME 이름, PAY 급여
FROM T_PROFESSOR 
WHERE pay > 500
;

UPDATE T_STUDENT SET 



INSERT INTO T_STUDENT (STUDNO , NAME , ID , DEPTNO1 , GRADE , PROFNO )
VALUES (9091, '김수진' , 'sooplus', 101, 2, 1004);

UPDATE T_STUDENT 
SET BIRTHDAY 


