-- 산술연산자

SELECT ENAME , SAL , SAL * 1.1 "급여 10% 인상금"
FROM T_EMP ;

SELECT ENAME ,SAL ,COMM 
FROM T_EMP ;

-- 급여와 교통비를 합산

SELECT  ENAME , SAL , COMM , COMM + SAL  -- null 값과의 산술 연산은 무조건 NULL!!
FROM T_EMP ;

-- WHERE 조건 절

SELECT *
FROM T_EMP WHERE job = 'SALESMAN' ;  -- WHERE 절에서는 = 가 비교문자 // ' '(문자열) 안에 대소문자 구별한다!!

-- p13
SELECT ename , sal , edeptno 
FROM T_EMP 
WHERE DEPTNO = 10;

SELECT ename , sal 
FROM T_EMP 
WHERE SAL > 2000;

SELECT ENAME ,EMPNO ,SAL 
FROM T_EMP 
WHERE ENAME ='SCOTT';

SELECT NAME , GRADE 
FROM T_STUDENT 
WHERE GRADE BETWEEN 2 AND 3;

SELECT  NAME , GRADE 
FROM T_STUDENT 
WHERE GRADE = 2 OR GRADE = 3;

SELECT NAME , GRADE 
FROM T_STUDENT 
WHERE GRADE IN (2,3);

SELECT NAME , GRADE 
FROM T_STUDENT 
WHERE GRADE > 1 AND GRADE < 4;

SELECT NAME , GRADE 
FROM T_STUDENT 
WHERE GRADE NOT IN (1,4);

SELECT NAME, PAY , "POSITION" 
FROM T_PROFESSOR 
WHERE PAY > 300 AND "POSITION" = '정교수';

SELECT NAME ,"POSITION" 
FROM T_PROFESSOR 
WHERE BONUS IS NULL;

SELECT NAME 
FROM T_PROFESSOR 
WHERE NAME LIKE '김%';

SELECT  ENAME 
FROM T_EMP 
WHERE ENAME LIKE '%NE%';

SELECT ENAME 
FROM T_EMP 
WHERE ENAME LIKE '_A%'; -- _위치에 어떤 글자라도 한글자 와야한다!!

SELECT  ENAME 
FROM T_EMP 
WHERE ENAME LIKE '%L%'
ORDER BY ENAME DESC ;

SELECT ENAME, JOB , SAL 
FROM T_EMP  
ORDER BY job DESC, SAL ASC ;

SELECT NAME , GRADE , HEIGHT
FROM T_STUDENT 
ORDER BY GRADE ASC , HEIGHT DESC ;
