-- DB03 ppt 
-- p25~ p 27까지 12개 쿼리짜기

SELECT *
FROM T_STUDENT ;

SELECT NAME
FROM T_STUDENT 
WHERE HEIGHT >= 180;

SELECT NAME , WEIGHT 
FROM T_STUDENT 
WHERE WEIGHT BETWEEN 60 AND 80;

SELECT NAME 
FROM T_STUDENT 
WHERE DEPTNO1 IN (101,201);

SELECT NAME 
FROM T_STUDENT 
WHERE NAME LIKE '김%';

SELECT  NAME, GRADE, HEIGHT 
FROM T_STUDENT 
WHERE GRADE = 4 AND HEIGHT >= 170;

SELECT  NAME ,HEIGHT ,GRADE ,WEIGHT 
FROM T_STUDENT 
WHERE WEIGHT >= 80 OR GRADE = 1;

SELECT  NAME ,GRADE ,HEIGHT ,WEIGHT 
FROM T_STUDENT 
WHERE HEIGHT >= 180 AND WEIGHT >= 70;

SELECT NAME ,GRADE ,HEIGHT ,WEIGHT 
FROM T_STUDENT 
WHERE GRADE = 2 and
(HEIGHT > 180 OR WEIGHT > 70);

SELECT ENAME n, HIREDATE 
FROM T_EMP 
WHERE HIREDATE < '1992-01-01';

SELECT NAME , BIRTHDAY , HEIGHT ,WEIGHT 
FROM T_STUDENT 
WHERE GRADE = 1 
ORDER BY BIRTHDAY ASC ;

SELECT  NAME 이름,HEIGHT 키 
FROM T_STUDENT 
ORDER BY NAME ASC ;

SELECT NAME , BIRTHDAY 
FROM T_EMP2 
WHERE BIRTHDAY BETWEEN '1980-01-01' AND '1989-12-31';

