CREATE INDEX idx_student_name ON t_student(name);

SELECT p.NAME "교수님 이름", d.DNAME "소속 학과명" FROM T_PROFESSOR p , T_DEPARTMENT d WHERE p.DEPTNO  = d.DEPTNO ;

SELECT s.NAME "학생이름", d.DNAME 
FROM T_STUDENT s, T_DEPARTMENT d 
WHERE s.DEPTNO1 = d.DEPTNO AND s.DEPTNO1 = (SELECT DEPTNO1 FROM T_STUDENT WHERE NAME = '이윤나');

SELECT DEPTNO1 FROM T_STUDENT WHERE NAME = '이윤나';

SELECT * FROM T_STUDENT ;

CREATE OR REPLACE VIEW v_stud_info (sname, dname, pname)
AS
SELECT s.NAME , d.DNAME , p.NAME 
FROM T_STUDENT s, T_PROFESSOR p , T_DEPARTMENT d
WHERE s.DEPTNO1 = d.DEPTNO AND p.PROFNO = s.PROFNO 
;

SELECT * FROM v_stud_info;

ALTER TABLE T_STUDENT 
ADD (BIRTHDAY DATE);

DROP TABLE T_MEMBER CASCADE CONSTRAINT;
CREATE TABLE T_MEMBER (
 mb_uid NUMBER,
 mb_name VARCHAR2(20) NOT NULL,
 mb_jumin VARCHAR2(13),
 mb_age NUMBER,
 mb_dept NUMBER,
 PRIMARY KEY(mb_uid),
 UNIQUE(mb_jumin),
 CHECK(mb_age > 0),
 FOREIGN KEY(mb_dept) REFERENCES t_dept(dcode)
);




